### ISSUE TITLE
Netatmo Presence not shown

### ISSUE THREAD

**Issue by fisch55** [ssadams11/node-red-contrib-netatmo#15]
Hi,

is it possible to get the Netatmo presence in the node?

**Comment by Anthony-vdm** [comment]
This would definitely be a plus to also get the Netatmo presence in the node with the Netatmo welcome cameras

**Comment by ssadams11** [comment]
I am no longer updating this code as I haven’t had a Netatmo device to test it with for several years.  It’s quite simple code, so fork the repo and take a shot at extending it for your needs.  
Regards
Sam

**Comment by Anthony-vdm** [comment]
I have checked and the netatmo presence has nothing to do with this code.

It is instead the authentication scope missing in the netatmo.js (dependency)

To fix it, update the netatmo.js by changing the scope = ... with the following line
scope = args.scope || 'read_station read_thermostat write_thermostat read_camera write_camera access_camera read_presence access_presence read_smokedetector read_homecoach';

You will then see the presence cameras (read_presence access_presence)

**Comment by ecdlguy** [comment]
@Anthony-vdm  can you please create a pull request for your netatmo presence fix?
cheers, Thorsten

**Comment by Anthony-vdm** [comment]
@ecdlguy 

I have made a pull request on Sep 28 on the netatmo project managed by @floetenbaer on which this node-red-contrib-netatmo has a dependency: https://github.com/floetenbaer/netatmo/pulls

Changing the netatmo.js file on line 96 and restarting node red will allow you to get the netatmo presence information
