### ISSUE TITLE
"Error: Authenticate refresh error: invalid_grant" on get_public_data

### ISSUE THREAD

**Issue by woody4165** [ssadams11/node-red-contrib-netatmo#16]
Hi @ssadams11 

I'm getting the error "Error: Authenticate refresh error: invalid_grant" when using get_public_data node.

This is the node configuration.

I've changed the LAT/LON data and I've hidden the `creds` field

Since I'm trying to get public data (I  don't have my own weather station) what info should I fill in the `creds` field? 
I've used my Netatmo thermostat data (username/password and mac address) to create the `creds` with the `ClientID` and `Client Secret` generated from https://dev.netatmo.com/

![Schermata 2020-03-02 alle 11 56 46](https://user-images.githubusercontent.com/6501444/75670410-f6878c80-5c7c-11ea-89ce-7721a939ec3e.png)

What else can I check?

Thanks

**Comment by ssadams11** [comment]
I haven't updated this in years as I no longer have any Netatmo devices.  Its quite possible that Netatmo has change/upgraded their authentication procedures.
Feel free to fork.  Its actually takes very little code to create your own node types in Node-RED.
Regards,
Sam

**Comment by woody4165** [comment]
ok, thanks
