### ISSUE TITLE
NPM Package Update

### ISSUE THREAD

**Issue by matthiasbaldi** [ssadams11/node-red-contrib-netatmo#18]
I saw here on Github that you still update this package.
But you may did not update the npm package.
Would you consider to also update the npm package? Because this would simplify the update mechanisms.

Thanks for an answer. 👍

**Comment by floetenbaer** [comment]
@ssadams11: If you like, I can assist you by maintaining this repro to keep it up-to-date.

**Comment by ssadams11** [comment]
Thanks.  I don’t even have any devices to test on anymore.
You should see an invite

Regards,
Sam

**Comment by floetenbaer** [comment]
@ssadams11  Thanks. Please add me as npm maintainer as well. My npm User is floetenbaer. Thx

Go to 'Admin' tab on your package page and invite maintainer (simply type in npm user login you want to be collaborator).
Press button 'Update Package Settings' above 'Maintainers' block.
