### ISSUE TITLE
Failed to install on Node-Red (Redmatic)

### ISSUE THREAD

**Issue by superpower10** [ssadams11/node-red-contrib-netatmo#24]
I used to have the version 0.2.x on my Node-Red and it worked fine.

Then I tried to update and it didn't work. So I deinstalled it, rebooted and tried to install it again. Same error:

error while loading shared libraries: libcurl.so.4: wrong ELF class: ELFCLASS64

Could anybody please help?

Thank you

**Comment by S474N** [comment]
You can try install/update this:
`sudo apt-get install -y libcurl4-gnutls-dev libjansson-dev`
