### ISSUE TITLE
Having the thermostat information

### ISSUE THREAD

**Issue by nekloth** [ssadams11/node-red-contrib-netatmo#3]
Hello,

User of your node, I also need to get my Netatmo thermostat information.

It seems to be possible to do it with the node package of karbassi, but not with your node-red package...

Thanks in advance !

**Comment by ssadams11** [comment]
Glad you are getting value from it.   I myself don't have a thermostat to test with.   Feel free to fork and play.  It's really simple code and not much of it.   
Cloning one of the existing nodes and hacking it for the thermostat API should be relatively easy.

**Comment by nekloth** [comment]
Arrgg... I'm not good at coding... I may try to fork, but I don't even know where to start to code it (html/js/npm...)

Ok, anyway, thank you ! :)

**Comment by ssadams11** [comment]
try https://nodered.org/docs/creating-nodes/

Thats the guide I followed.
Try the example they use first to get the idea.

And have fun!!

Regards,
Sam


Sam S. Adams, Cognitive Eldercare
IBM Master Inventor, IBM Academy of Technology
IBM Distinguished Engineer, IBM Research
Mobile: 919-696-6064, email: ssadams@us.ibm.com
Assistant: Jill Taylor/Austin/Contr/IBM, jillmcn@us.ibm.com, 720-430-9048
<<Hebrews 11:6, Proverbs 3:5-6, Romans 1:16-17, 1 Corinthians 1:10>>

**Comment by nekloth** [comment]
OK, I'll try.

Thank you.

**Comment by nekloth** [comment]
Final question: do you suggest an evolution of your package or a new package dedicated for the Thermostat

(first answer will lead me to fin another npm node-red package name...)

**Comment by ssadams11** [comment]
You could build a separate package for thermostat only,
node-red-contrib-netatmo-thermostat.  That might be easier.  Use any of my
code you want.
Then I could reintegrate you work later into a more complete package.

Or you could just fork and enhance my package, save it as
node-red-contrib-netatmo-nek or something so you can use it directly, then
I could jsut accpet your enhacnements and republish a new version of the
whole package.

Regards,
Sam


Sam S. Adams, Cognitive Eldercare
IBM Master Inventor, IBM Academy of Technology
IBM Distinguished Engineer, IBM Research
Mobile: 919-696-6064, email: ssadams@us.ibm.com
Assistant: Jill Taylor/Austin/Contr/IBM, jillmcn@us.ibm.com, 720-430-9048
<<Hebrews 11:6, Proverbs 3:5-6, Romans 1:16-17, 1 Corinthians 1:10>>

**Comment by nekloth** [comment]
Thank you for your answer. 
Sorry if my question was stupid, I'm not familiar enough with fork/branch/merge etc...

I have a first working version of thermostat packages but there are side effects. I'll try to see how to solve them (but it is maybe on @karbassi project ... or Netatmo side)

**Comment by ssadams11** [comment]
No problem.  I've only done one fork-pull myself.

We all learning!  ;-)

Regards,
Sam


Sam S. Adams, Cognitive Eldercare
IBM Master Inventor, IBM Academy of Technology
IBM Distinguished Engineer, IBM Research
Mobile: 919-696-6064, email: ssadams@us.ibm.com
Assistant: Jill Taylor/Austin/Contr/IBM, jillmcn@us.ibm.com, 720-430-9048
<<Hebrews 11:6, Proverbs 3:5-6, Romans 1:16-17, 1 Corinthians 1:10>>

**Comment by nekloth** [comment]
Yep !

Thank you

**Comment by nekloth** [comment]
Hello,

Just to let you know I publish a node dedicated for the Netatmo thermostat:

https://www.npmjs.com/package/node-red-contrib-netatmo-thermostat
&
https://github.com/nekloth/node-red-contrib-netatmo

Thank you for your help !
Nekloth

**Comment by nekloth** [comment]
Done somewhere else ;-)
