### ISSUE TITLE
Node-red fails to load , when node-red-contrib-netatmo is installed 

### ISSUE THREAD

**Issue by pulsejets** [ssadams11/node-red-contrib-netatmo#9]
![screenshot from 2018-01-13 23-00-17](https://user-images.githubusercontent.com/13909016/34910835-7b475fde-f8bd-11e7-91a3-38dbe6229f23.png)

I have also tried to do a clean install , with only node-red-contrib-netatmo installed
 npm install -g --unsafe-perm node-red
 npminstall  node-red-contrib-netatmo -g

**Comment by ghost** [comment]
Some problem here. Unfortunately I don't know how to further debug this. Any idea?

**Comment by ssadams11** [comment]
Same thing happened to me yesterday.  What version of Nodered are you running?

**Comment by ghost** [comment]
It's an Ubuntu 16 LTS with Node 7.10.1 which is the current version bundled with Ubuntu.

**Comment by sebastiandeppisch** [comment]
I have the same error. 
The netatmoNodes.html is full of merge conflicts (as you can see on the screenshot)
How to reproduce: 
Create a new project with npm and install this node (without node-red). Then take a look at the netatmoNodes.html file.

Tested on: Ubuntu 17.10. npm 5.6.0 node 8.9.4
And: Raspbian Jessie with npm 5.0.4 node 8.1.3 node-red 0.17.5

**Comment by igor-levkov** [comment]
Yep, last commit brought some troubles. This one works just fine:
https://github.com/ssadams11/node-red-contrib-netatmo/tree/ac650175cc7b802d80fc8c93b8c28156c1bfc3a7

**Comment by jensfr1** [comment]
I am using
11 Mar 17:09:24 - [info] Node-RED version: v0.18.4
11 Mar 17:09:24 - [info] Node.js  version: v9.8.0
and only the first 3 items 
get next events
get camera picture
get home data
are marked green in node-red. Dont get any error during instalation. Any idea if that Is a similar issue then this? 
Thanks, Jens

**Comment by osos** [comment]
I think I fixed it with this pull request: https://github.com/ssadams11/node-red-contrib-netatmo/pull/10

**Comment by osos** [comment]
Try latest master

**Comment by ssadams11** [comment]
Thanks for all the help and effort and nagging (a good thing!)
version 0.2.0 loads and runs successfully in node-red 0.18.3
